/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { MeshRefractionMaterial, useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

type GLTFResult = GLTF & {
  nodes: {
    Desk: THREE.Mesh
    Lamp_Base: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder005: THREE.Mesh
    Ring: THREE.Mesh
    Cylinder012_1: THREE.Mesh
    Cylinder012_2: THREE.Mesh
    Cylinder014: THREE.Mesh
    Cylinder014_1: THREE.Mesh
    Cylinder015: THREE.Mesh
    Cylinder015_1: THREE.Mesh
    Cylinder016: THREE.Mesh
    Cylinder016_1: THREE.Mesh
    Cylinder010: THREE.Mesh
    Cylinder011: THREE.Mesh
    Cylinder012: THREE.Mesh
    Cylinder013: THREE.Mesh
  }
  materials: {
    SofterWood: THREE.MeshPhysicalMaterial
    Metal: THREE.MeshStandardMaterial
    Gold: THREE.MeshStandardMaterial
    Glass: THREE.MeshPhysicalMaterial
    Plastic: THREE.MeshStandardMaterial
  }
}

export function Desk(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/desk/desk.gltf') as GLTFResult;

  return (
    <group {...props} dispose={null} rotation-y={Math.PI * -.5}>
      <mesh receiveShadow geometry={nodes.Desk.geometry} material={materials.SofterWood} position={[0, -0.49, 0]} scale={[9.25, 23.94, 15.41]} />
      <mesh castShadow receiveShadow geometry={nodes.Lamp_Base.geometry} material={materials.Metal} position={[-7.73, -0.75, -11.17]} rotation={[0, 0.75, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={materials.Metal} position={[0, -0.33, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={materials.Metal} position={[1.52, -0.33, 1.43]} rotation={[0, 0.93, 0]} scale={0.57} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder002.geometry} material={materials.Metal} position={[1.52, -0.33, 1.43]} rotation={[0, 0.93, 0]} scale={0.57} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder003.geometry} material={materials.Metal} position={[-1.52, -0.33, -1.43]} rotation={[0, 0.93, 0]} scale={0.57} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder004.geometry} material={materials.Metal} position={[-1.52, -0.33, 1.43]} rotation={[0, 0.93, 0]} scale={0.57} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder005.geometry} material={materials.Metal} position={[1.52, -0.33, -1.43]} rotation={[0, 0.93, 0]} scale={0.57} />
      <mesh castShadow receiveShadow geometry={nodes.Ring.geometry} material={materials.Gold} position={[0, -0.33, 0]} scale={3.08} />
      <group position={[2, -0.33, 0]} rotation={[0, 0.93, 0]} scale={0.57}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder012_1.geometry} material={materials.Gold} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder012_2.geometry} material={materials.Glass} />
      </group>
      <group position={[-2, -0.33, 0]} rotation={[0, 0.93, 0]} scale={0.57}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder014.geometry} material={materials.Gold} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder014_1.geometry} material={materials.Glass} />
      </group>
      <group position={[0, -0.33, -2]} rotation={[0, 0.93, 0]} scale={0.57}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder015.geometry} material={materials.Gold} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder015_1.geometry} material={materials.Glass} />
      </group>
      <group position={[0, -0.33, 2]} rotation={[0, 0.93, 0]} scale={0.57}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder016.geometry} material={materials.Gold} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder016_1.geometry} material={materials.Glass} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Cylinder010.geometry} material={materials.Plastic} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder011.geometry} material={materials.Plastic} position={[-2.01, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder012.geometry} material={materials.Plastic} position={[-2, 0, -2]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder013.geometry} material={materials.Plastic} position={[-2, 0, 2]} />
    </group>
  )
}

useGLTF.preload('/desk.gltf')
