/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder005: THREE.Mesh
    Ring: THREE.Mesh
    Cylinder012_1: THREE.Mesh
    Cylinder012_2: THREE.Mesh
    Cylinder014_1: THREE.Mesh
    Cylinder014_2: THREE.Mesh
    Cylinder015_1: THREE.Mesh
    Cylinder015_2: THREE.Mesh
    Cylinder016_1: THREE.Mesh
    Cylinder016_2: THREE.Mesh
    Cylinder010: THREE.Mesh
    Cylinder011: THREE.Mesh
    Cylinder012: THREE.Mesh
    Cylinder013: THREE.Mesh
    Icosphere: THREE.Mesh
    Icosphere001: THREE.Mesh
    Icosphere002: THREE.Mesh
    Icosphere003: THREE.Mesh
    Icosphere004: THREE.Mesh
    Icosphere005: THREE.Mesh
    Ring002: THREE.Mesh
    Ring003: THREE.Mesh
    Cube002: THREE.Mesh
    Cube002_1: THREE.Mesh
    Cube002_2: THREE.Mesh
    Cube002_3: THREE.Mesh
    Cube002_4: THREE.Mesh
    Cube002_5: THREE.Mesh
    Ring001: THREE.Mesh
    Ring004: THREE.Mesh
    Ring005: THREE.Mesh
    Vert001: THREE.Mesh
    Cylinder010_1: THREE.Mesh
    Cylinder010_2: THREE.Mesh
    Cylinder010_3: THREE.Mesh
    Cylinder010_4: THREE.Mesh
    Cylinder010_5: THREE.Mesh
    Cylinder010_6: THREE.Mesh
    Cylinder010_7: THREE.Mesh
    Mesh: THREE.Mesh
    Mesh_1: THREE.Mesh
    Mesh_2: THREE.Mesh
    Mesh002: THREE.Mesh
    Mesh002_1: THREE.Mesh
    Mesh002_2: THREE.Mesh
    Mesh003: THREE.Mesh
    Mesh003_1: THREE.Mesh
    Mesh003_2: THREE.Mesh
    Mesh004: THREE.Mesh
    Mesh004_1: THREE.Mesh
    Mesh004_2: THREE.Mesh
    Mesh005: THREE.Mesh
    Mesh005_1: THREE.Mesh
    Mesh005_2: THREE.Mesh
    Solid_1: THREE.Mesh
    Solid_2: THREE.Mesh
    Solid_3: THREE.Mesh
    Solid_4: THREE.Mesh
    Mesh006: THREE.Mesh
    Mesh006_1: THREE.Mesh
    Mesh006_2: THREE.Mesh
    Cylinder018: THREE.Mesh
    Cylinder013_1: THREE.Mesh
    Cylinder013_2: THREE.Mesh
    Cylinder020: THREE.Mesh
    Cylinder022_1: THREE.Mesh
    Cylinder022_2: THREE.Mesh
    Cylinder023_1: THREE.Mesh
    Cylinder023_2: THREE.Mesh
    Cylinder024_1: THREE.Mesh
    Cylinder024_2: THREE.Mesh
    Cylinder025_1: THREE.Mesh
    Cylinder025_2: THREE.Mesh
    Cylinder025: THREE.Mesh
    Cylinder026: THREE.Mesh
    Cylinder027: THREE.Mesh
    pipe_diagram: THREE.Mesh
    Cylinder_1: THREE.Mesh
    Cylinder_2: THREE.Mesh
    Cylinder_3: THREE.Mesh
    Cylinder002_1: THREE.Mesh
    Cylinder002_2: THREE.Mesh
    Cylinder002_3: THREE.Mesh
    Cylinder003_1: THREE.Mesh
    Cylinder003_2: THREE.Mesh
    Cylinder003_3: THREE.Mesh
  }
  materials: {
    SofterWood: THREE.MeshPhysicalMaterial
    Metal: THREE.MeshStandardMaterial
    Rubber: THREE.MeshStandardMaterial
    Gold: THREE.MeshStandardMaterial
    ['Glass.001']: THREE.MeshStandardMaterial
    Plastic: THREE.MeshStandardMaterial
    Crystal: THREE.MeshPhysicalMaterial
    CrystalGreen: THREE.MeshPhysicalMaterial
    CrystalRed: THREE.MeshPhysicalMaterial
    Wood: THREE.MeshStandardMaterial
    Glass: THREE.MeshPhysicalMaterial
    Brass: THREE.MeshStandardMaterial
    WhitePlastic: THREE.MeshStandardMaterial
    LightMetal: THREE.MeshStandardMaterial
    LightPoles: THREE.MeshStandardMaterial
    LightBulb: THREE.MeshStandardMaterial
    paper: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
    pipe_diagram: THREE.MeshStandardMaterial
  }
}

export function Desk(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/desk/desk.gltf') as GLTFResult
  
  useEffect(() => {
    materials.SofterWood.toneMapped = false;
    // materials.Metal.toneMapped = false;
    materials.Rubber.toneMapped = false;
    materials.Gold.toneMapped = false;
    materials.Plastic.toneMapped = false;
    materials.Crystal.toneMapped = false;
    materials.CrystalGreen.toneMapped = false;
    materials.CrystalRed.toneMapped = false;
    // materials.Wood.toneMapped = false;
    materials.Glass.toneMapped = false;
    materials.Brass.toneMapped = false;
    // materials.WhitePlastic.toneMapped = false;
    materials.LightMetal.toneMapped = false;
    materials.LightPoles.toneMapped = false;
    materials.LightBulb.toneMapped = false;
    // materials.paper.toneMapped = false;
    // materials.Red.toneMapped = false;
    materials.pipe_diagram.toneMapped = false;
  });

  return (
    <group {...props} dispose={null} rotation-y={Math.PI * -.5}>
      <group position={[0, -0.49, 0]} scale={[9.25, 23.94, 15.41]}>
        <mesh receiveShadow geometry={nodes.Plane.geometry} material={materials.SofterWood} />
        <mesh receiveShadow geometry={nodes.Plane_1.geometry} material={materials.Metal} />
        <mesh receiveShadow geometry={nodes.Plane_2.geometry} material={materials.Rubber} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={materials.Metal} position={[0, -0.33, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={materials.Metal} position={[1.52, -0.33, 1.43]} rotation={[0, 0.93, 0]} scale={0.57} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder002.geometry} material={materials.Metal} position={[1.52, -0.33, 1.43]} rotation={[0, 0.93, 0]} scale={0.57} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder003.geometry} material={materials.Metal} position={[-1.52, -0.33, -1.43]} rotation={[0, 0.93, 0]} scale={0.57} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder004.geometry} material={materials.Metal} position={[-1.52, -0.33, 1.43]} rotation={[0, 0.93, 0]} scale={0.57} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder005.geometry} material={materials.Metal} position={[1.52, -0.33, -1.43]} rotation={[0, 0.93, 0]} scale={0.57} />
      <mesh castShadow receiveShadow geometry={nodes.Ring.geometry} material={materials.Gold} position={[0, -0.33, 0]} scale={3.08} />
      <group position={[2, -0.33, 0]} rotation={[0, 0.93, 0]} scale={0.57}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder012_1.geometry} material={materials.Gold} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder012_2.geometry} material={materials['Glass.001']} />
      </group>
      <group position={[-2, -0.33, 0]} rotation={[0, 0.93, 0]} scale={0.57}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder014_1.geometry} material={materials.Gold} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder014_2.geometry} material={materials['Glass.001']} />
      </group>
      <group position={[0, -0.33, -2]} rotation={[0, 0.93, 0]} scale={0.57}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder015_1.geometry} material={materials.Gold} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder015_2.geometry} material={materials['Glass.001']} />
      </group>
      <group position={[0, -0.33, 2]} rotation={[0, 0.93, 0]} scale={0.57}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder016_1.geometry} material={materials.Gold} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder016_2.geometry} material={materials['Glass.001']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Cylinder010.geometry} material={materials.Plastic} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder011.geometry} material={materials.Plastic} position={[-2.01, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder012.geometry} material={materials.Plastic} position={[-2, 0, -2]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder013.geometry} material={materials.Plastic} position={[-2, 0, 2]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere.geometry} material={materials.Crystal} position={[0.92, -0.16, 10.37]} rotation={[1.43, 0.48, 0.02]} scale={[0.34, 0.82, 0.34]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere001.geometry} material={materials.Crystal} position={[1.55, -0.06, 10.52]} rotation={[1.66, -0.52, -1.52]} scale={[0.32, 0.8, 0.26]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere002.geometry} material={materials.Crystal} position={[0.95, -0.02, 11.48]} rotation={[1.83, -0.27, 1.32]} scale={[0.48, 1.16, 0.48]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere003.geometry} material={materials.CrystalGreen} position={[0.08, -0.32, 9.52]} rotation={[-2.03, -0.47, -0.69]} scale={[0.32, 0.8, 0.26]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere004.geometry} material={materials.CrystalGreen} position={[0.03, -0.06, 10.46]} rotation={[2.05, 1.29, 2.85]} scale={[0.24, 0.97, 0.37]} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere005.geometry} material={materials.CrystalRed} position={[-5.13, 3.1, 11.49]} rotation={[0, 0.38, 0]} scale={[0.59, 1.4, 0.59]} />
      <mesh castShadow receiveShadow geometry={nodes.Ring002.geometry} material={materials.Gold} position={[-5.1, 1.86, 11.46]} rotation={[0, 0.38, 0]} scale={0.34} />
      <mesh castShadow receiveShadow geometry={nodes.Ring003.geometry} material={materials.Gold} position={[-5.15, 3.08, 11.46]} rotation={[0, 0.38, 0]} scale={0.83} />
      <group position={[-5.36, 0.13, 10.78]} rotation={[0, 0.38, 0]} scale={[1.14, 1.11, 1.23]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube002_1.geometry} material={materials.Wood} />
        <mesh castShadow receiveShadow geometry={nodes.Cube002_2.geometry} material={materials.Gold} />
        <mesh castShadow receiveShadow geometry={nodes.Cube002_3.geometry} material={materials['Glass.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube002_4.geometry} material={materials.Plastic} />
        <mesh castShadow receiveShadow geometry={nodes.Cube002_5.geometry} material={materials.SofterWood} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Ring001.geometry} material={materials.Gold} position={[-5.1, 2.46, 11.46]} rotation={[0, 0.38, 0]} scale={0.68} />
      <mesh castShadow receiveShadow geometry={nodes.Ring004.geometry} material={materials.Gold} position={[-5.1, 3.73, 11.46]} rotation={[0, 0.38, 0]} scale={0.68} />
      <mesh castShadow receiveShadow geometry={nodes.Ring005.geometry} material={materials.Gold} position={[-5.1, 4.15, 11.46]} rotation={[0, 0.38, 0]} scale={0.34} />
      <mesh castShadow receiveShadow geometry={nodes.Vert001.geometry} material={materials.Glass} position={[-6.04, 4.03, 9.69]} rotation={[0, 0.38, 0]} scale={1.11} />
      <group position={[-4.91, -0.33, -12.67]} rotation={[0, 0.45, 0]} scale={[2.09, 1.54, 2.09]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder010_1.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder010_2.geometry} material={materials.Brass} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder010_3.geometry} material={materials.WhitePlastic} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder010_4.geometry} material={materials.LightMetal} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder010_5.geometry} material={materials.LightPoles} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder010_6.geometry} material={materials.Plastic} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder010_7.geometry} material={materials.LightBulb} />
      </group>
      <group position={[-5.76, 0.04, 4.65]} rotation={[-1.56, 0.15, -3.06]} scale={0.18}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh.geometry} material={materials.paper} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_1.geometry} material={materials.CrystalRed} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_2.geometry} material={materials.Red} />
      </group>
      <group position={[-6.89, 0.11, 4.65]} rotation={[-1.56, 0.15, -3.06]} scale={[0.18, 0.21, 0.18]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh002.geometry} material={materials.paper} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh002_1.geometry} material={materials.CrystalRed} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh002_2.geometry} material={materials.Red} />
      </group>
      <group position={[-6.68, 0.43, 1.14]} rotation={[-1.94, 1.03, -2.96]} scale={0.18}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh003.geometry} material={materials.paper} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh003_1.geometry} material={materials.CrystalRed} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh003_2.geometry} material={materials.Red} />
      </group>
      <group position={[-6.04, -0.13, 1.38]} rotation={[-1.42, 0.05, 2.05]} scale={0.15}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh004.geometry} material={materials.paper} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh004_1.geometry} material={materials.CrystalRed} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh004_2.geometry} material={materials.Red} />
      </group>
      <group position={[-6.21, 0.73, 4.78]} rotation={[-1.93, 1.04, -2.73]} scale={0.16}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh005.geometry} material={materials.paper} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh005_1.geometry} material={materials.CrystalRed} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh005_2.geometry} material={materials.Red} />
      </group>
      <group position={[0.79, 0.38, -10.08]} rotation={[-1.07, 0.17, 0.25]}>
        <mesh castShadow receiveShadow geometry={nodes.Solid_1.geometry} material={materials.Gold} />
        <mesh castShadow receiveShadow geometry={nodes.Solid_2.geometry} material={materials.CrystalGreen} />
        <mesh castShadow receiveShadow geometry={nodes.Solid_3.geometry} material={materials['Glass.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Solid_4.geometry} material={materials.Metal} />
      </group>
      <group position={[-6.82, 0.05, -3.68]} rotation={[-1.59, 0.15, -2.87]} scale={[0.2, 0.4, 0.2]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh006.geometry} material={materials.paper} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh006_1.geometry} material={materials.CrystalRed} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh006_2.geometry} material={materials.Red} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Cylinder018.geometry} material={materials.Metal} position={[4.79, -0.33, -8.27]} rotation={[0, 0.93, 0]} scale={0.28} />
      <group position={[4.33, -0.37, -8.73]} rotation={[0, 0.93, 0]} scale={0.24}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder013_1.geometry} material={materials.Gold} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder013_2.geometry} material={materials['Glass.001']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Cylinder020.geometry} material={materials.Metal} position={[5.36, -0.35, -8.63]} rotation={[3.01, 0.87, -2.94]} scale={0.38} />
      <group position={[6.41, -0.29, -8.67]} rotation={[2.41, 0.51, -1.11]} scale={[1.64, 1.21, 1.64]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder022_1.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder022_2.geometry} material={materials.WhitePlastic} />
      </group>
      <group position={[6.48, -0.33, -8.83]} rotation={[2.41, 0.51, -1.11]} scale={[1.64, 1.21, 1.64]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder023_1.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder023_2.geometry} material={materials.WhitePlastic} />
      </group>
      <group position={[6.15, -0.33, -9.12]} rotation={[-2.34, -0.23, -1.36]} scale={[1.64, 1.21, 1.64]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder024_1.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder024_2.geometry} material={materials.WhitePlastic} />
      </group>
      <group position={[6.23, -0.23, -8.61]} rotation={[-1.82, -0.58, -1.23]} scale={[1.64, 1.21, 1.64]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder025_1.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder025_2.geometry} material={materials.WhitePlastic} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Cylinder025.geometry} material={materials.Metal} position={[4.56, -0.33, 3.92]} rotation={[3.05, 0.59, -3.04]} scale={0.38} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder026.geometry} material={materials.Metal} position={[-0.89, -0.34, 6.32]} rotation={[1.2, 1.49, -1.15]} scale={[0.24, 0.42, 0.24]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder027.geometry} material={materials.Gold} position={[7.06, -0.33, 9.56]} rotation={[3.06, 0.12, -3.08]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes.pipe_diagram.geometry} material={materials.pipe_diagram} position={[2.95, -0.42, 7.97]} rotation={[-Math.PI, 1.16, -Math.PI]} scale={6.38} />
      <group position={[3.81, -0.19, -10.28]} rotation={[-0.04, 1.02, 1.58]} scale={[0.16, 0.56, 0.16]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder_1.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder_2.geometry} material={materials.Wood} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder_3.geometry} material={materials.paper} />
      </group>
      <group position={[5.43, -0.26, -9.63]} rotation={[-0.63, 0.15, 1.66]} scale={[0.11, 0.39, 0.11]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder002_1.geometry} material={materials.Glass} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder002_2.geometry} material={materials.Wood} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder002_3.geometry} material={materials.paper} />
      </group>
      <group position={[5.4, -0.26, -10.82]} rotation={[-1.01, -0.18, 1.31]} scale={[0.11, 0.53, 0.11]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder003_1.geometry} material={materials.Glass} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder003_2.geometry} material={materials.Wood} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder003_3.geometry} material={materials.paper} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/desk/desk.gltf')
